name: TidyWGSPy3.5
channels: !!python/tuple
- bioconda
- conda-forge
- defaults
dependencies:
- perl-vcftools-vcf
- vcflib
- vcftools
- damianavila82::rise
- python=3.5
- babel
- bokeh
- csvkit
- cython
- cytoolz
- dask
- datashader
- hdf5
- ioam::holoviews
- ipykernel
- ipython
- ipywidgets
- jupyter_client
- jupyter_console
- jupyter_core
- matplotlib
- mpi4py
- nbconvert
- networkx
- nltk
- notebook
- numba
- numexpr
- numpy
- pandas
- pytables
- pytest
- r-essentials
- scipy
- sphinx
- statsmodels
- pip:
  - gister
  - notedown
  - altair
  - ggplot
  - pybedtools
  - pyfaidx
  - pysam
  - pyvcf
  - rpy2
  - scikit-allel
  - scikit-bio
  - vcfnp
  - vega
