name: TidyWGSPy3.5
channels: !!python/tuple
- bioconda
- conda-forge
- defaults
dependencies:
- bwa
- perl-vcftools-vcf
- vcflib
- vcftools
- damianavila82::rise
- python=3.5
- babel
- biopython
- bokeh
- csvkit
- cython
- cytoolz
- dask
- datashader
- hdf5
- ioam::holoviews
- ipykernel
- ipython
- ipywidgets
- jupyter_client
- jupyter_console
- jupyter_core
- matplotlib
- mpi4py
- nbconvert
- networkx
- nltk
- notebook
- numba
- numexpr
- numpy
- opencv
- pandas
- pytables
- pytest
- r-essentials
- scikit-image
- scikit-learn
- scipy
- seaborn
- snakeviz
- sphinx
- sqlalchemy
- statsmodels
- sympy
- theano
- toolz
- xarray
- pip:
  - gister
  - notedown
  - altair
  - dendropy
  - ggplot
  - hdbscan
  - joblib
  - MDAnalysis
  - modulecmd
  - mypy
  - nbdime
  - palettable
  - pybedtools
  - pyfaidx
  - pysam
  - pyvcf
  - rpy2
  - scikit-allel
  - scikit-bio
  - vcfnp
  - vega
